// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrHZLiK7r9rttiokoIgO9kXMw3ZuVHRQI',
    appId: '1:625076401474:web:94d1fc80f886fc12af44db',
    messagingSenderId: '625076401474',
    projectId: 'accel-attend',
    authDomain: 'accel-attend.firebaseapp.com',
    storageBucket: 'accel-attend.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5JmQTqdgy5deMFBUF9FEmZP4aZ_k7SEk',
    appId: '1:625076401474:android:70408b37b58d7bdaaf44db',
    messagingSenderId: '625076401474',
    projectId: 'accel-attend',
    storageBucket: 'accel-attend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7m7ZXjP6OoSL4aIzx2aut3agda1nDIo',
    appId: '1:625076401474:ios:906f178e15d3af7aaf44db',
    messagingSenderId: '625076401474',
    projectId: 'accel-attend',
    storageBucket: 'accel-attend.firebasestorage.app',
    iosBundleId: 'com.example.sample',
  );

}